variables:
  PROJECT_NAME: "ImageSharp"
before_script:
  - echo "starting test for %PROJECT_NAME%"
stages:
  - test
test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2.300-bionic
  script:
  - apt-get update
  - apt-get -y install libgdiplus libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
  - git submodule -q update --init
  - dotnet restore
  - dotnet test tests/ImageSharp.Tests/ImageSharp.Tests.csproj -c Release -f "netcoreapp2.1"
  artifacts:
    untracked: true