language: csharp
mono: none
solution: ImageSharp.sln

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
 
services:
  - docker

branches:
  only:
    - master
    - feature/unitTestsWithDockerArm
    - coverity_scan

script:
  # setup QEMU
  - uname -r
  - docker run --rm --privileged hypriot/qemu-register
  - docker-compose build
  - docker-compose up