language: csharp
mono: none
solution: ImageSharp.sln

env:
  - ARCH=x32
  - ARCH=arm

matrix:
  include:
    - os: linux-aarch64
      dist: xenial
      sudo: required

services:
  - docker

branches:
  only:
    - master
    - feature/unitTestsWithDockerArm
    - coverity_scan

script:
  # setup QEMU
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose build
  - docker-compose up