language: csharp
solution: ImageSharp.sln

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: xenial
      sudo: required
      dotnet: 2.1.603
      mono: latest

services:
  - docker

branches:
  only:
    - master
    - feature/unitTestsWithDocker
    - coverity_scan

script:
  - git submodule -q update --init
  - docker-compose build
  - docker-compose up