language: csharp
solution: ImageSharp.sln

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: xenial
      sudo: required
      dotnet: 2.1.603
      mono: latest

branches:
  only:
    - master
    - feature/unitTestsWithDocker
    - coverity_scan

script:
  - git submodule -q update --init
  - dotnet restore
  - dotnet test tests/ImageSharp.Tests/ImageSharp.Tests.csproj -c Release -f "netcoreapp2.1"