language: csharp
mono: none
solution: ImageSharp.sln

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: xenial
      sudo: required

services:
  - docker

branches:
  only:
    - master
    - feature/unitTestsWithDocker
    - coverity_scan

script:
  - docker-compose build
  - docker-compose up